config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :vacations

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]

  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.all
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
  end

  # POST /vacations
  # POST /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation was successfully created.' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to vacations_url, notice: 'Vacation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_params
      params.require(:vacation).permit(:start_date, :end_date, :place)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vacations/_form.html.erb
<%= form_for(@vacation) do |f| %>
  <% if @vacation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

      <ul>
      <% @vacation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacations/edit.html.erb
<h1>Editing Vacation</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacation %> |
<%= link_to 'Back', vacations_path %>

app/views/vacations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vacations</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacations.each do |vacation| %>
      <tr>
        <td><%= vacation.start_date %></td>
        <td><%= vacation.end_date %></td>
        <td><%= vacation.place %></td>
        <td><%= link_to 'Show', vacation %></td>
        <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
        <td><%= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation', new_vacation_path %>

app/views/vacations/new.html.erb
<h1>New Vacation</h1>

<%= render 'form' %>

<%= link_to 'Back', vacations_path %>

app/views/vacations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @vacation.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @vacation.end_date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @vacation.place %>
</p>

<%= link_to 'Edit', edit_vacation_path(@vacation) %> |
<%= link_to 'Back', vacations_path %>